### ISSUE TITLE
Exchanges - Bittrex Issues?

### ISSUE THREAD

**Issue by Behner** [coinpride/CryptoList#52]
Seems to be a bit of unrest in the Bittrex camp, could that rating be lowered?

https://www.reddit.com/r/Bittrex/
https://www.google.com/search?safe=off&client=firefox-b-1-ab&biw=1680&bih=978&tbs=qdr%3Am&tbm=nws&ei=HCBYWqCdOYW5ggeE5pXQDw&q=bittrex&oq=bittrex&gs_l=psy-ab.12...0.0.0.7233.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.KYsRIR_83UI

**Comment by alexanderisora** [comment]
Fair enough. Done. Thanks.
